openapi: 3.0.2
info:
  title: 'POCOS_API'
  version: '0.01'
paths:
  /pocos/:
    get:
      operationId: listWells
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: bacia
        required: false
        in: query
        description: bacia
        schema:
          type: string
      - name: estado
        required: false
        in: query
        description: estado
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Well'
          description: ''
      tags:
      - pocos
  /pocos/{id}/:
    get:
      operationId: retrieveWellDetail
      description: Retrieve, update or delete a snippet instance.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - pocos
  /users/:
    get:
      operationId: listPoco_Users
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
          description: ''
      tags:
      - users
  /register/:
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - register
components:
  schemas:
    Well:
      type: object
      properties:
        id:
          type: string
          maxLength: 30
        bacia:
          type: string
          maxLength: 30
        estado:
          type: string
          maxLength: 30
        municipio:
          type: string
          maxLength: 30
        lat:
          type: number
        long:
          type: number
        formac:
          type: string
      required:
      - id
      - bacia
      - estado
      - municipio
      - lat
      - long
      - formac
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 254
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        password:
          type: string
          maxLength: 128
        profilepic:
          type: string
          format: binary
      required:
      - username
      - password
